dist: trusty
language: ruby
rvm:
  - 2.4.1
bundler_args: --without development
cache: bundler
addons:
  apt_packages:
    - pandoc
  code_climate:
    repo_token: TODO # Can be found here: On codeclimate.com, go to "Test coverage"
before_install:
  - export TZ=Europe/Zurich
before_script:
  - cp config/secrets.travis.yml config/secrets.yml
script:
  - RAILS_ENV=test bundle exec rails db:create
  - RAILS_ENV=test bundle exec rails db:migrate
  -                bundle exec rails spec
notifications:
  email:
    recipients:
      - john.doe@example.com # TODO
    on_failure: change
    on_success: change