dist: trusty
language: ruby
rvm:
  - 2.2.6
bundler_args: --without development
cache: bundler
addons:
  apt_packages:
    - pandoc
  code_climate:
    repo_token: TODO # Can be found here: On codeclimate.com, go to "Test coverage"
before_script:
  - cp config/secrets.travis.yml config/secrets.yml
script:
  - RAILS_ENV=test bundle exec rails db:setup
  - bundle exec rails spec
notifications:
  email:
    recipients:
      - john.doe@example.com # Change!
      - lisa.gonzales@example.com # Change!
    on_failure: change
    on_success: change