# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  app_port:                  TODO # Will be used for development and deployment, e.g. `3001`
  mailer_from:               TODO # Sender address in emails, e.g. `mailer@base.uber.space` (doesn't need to be the same as `smtp_user_name`, it can be any email, e.g. `info@my-cool-project.com` or `base@gmail.com`); if users reply to any email they received from the Rails app, the email will be sent to this address.
  smtp_authentication:       TODO # E.g. `login`
  smtp_address:              TODO # The SMTP server to login to, e.g. `base.uber.space` or `smtp.gmail.com`
  smtp_domain:               TODO # E.g. `base.uber.space` or `gmail.com`
  smtp_enable_starttls_auto: TODO # E.g. `false` (Uberspace) or `true` (Gmail)
  smtp_password:             TODO
  smtp_port:                 TODO # E.g. `587`
  smtp_ssl:                  TODO # E.g. `true`
  smtp_user_name:            TODO # E.g. `mailer@base.uber.space` or `base@gmail.com`
  default_url_host:          TODO # Domain that's prepended to links that are to be clicked outside of the Rails app (like in a sent email). For development and test, this should be `localhost`; this makes `Capybara.asset_host` work which allows nicer debugging of failing specs. For production, this should be something like `base.uber.space` (or a domain that is mapped to it, e.g. `www.my-cool-project.com`).
  http_auth_password:        TODO # The password for the HTTP authentication (only in production mode); user is `admin`.

development:
  <<: *default
  secret_key_base:   TODO # Use `$ rails secret`
  database_username: TODO
  database_password: TODO

test:
  <<: *default
  secret_key_base:   TODO # Use `$ rails secret`
  database_username: TODO
  database_password: TODO

# This is only needed on the production server! (You can remove `development` and `test` there.)
production:
  <<: *default
  secret_key_base:   TODO # Use `$ rails secret`
  database:          TODO
  database_username: TODO
  database_password: TODO
