# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9caab0e95a3fce64b8d15bca0a10bf749ace1823ab677c47b0327f479c274d840707ab9be11cf53c144197a86768f7dd16e53dfec881eef1b32634fdd4f5ff1
  database_username: root
  database_password: t00R

test:
  secret_key_base: bb1dbfcb1b0e98a6edde5155a4204edc09ff022c4010132fd6a8eade2261a70cbcf3ee5eb5de790b68ba8123d49f6668cf04376aa399adce49d558f89360864b
  database_username: root
  database_password: t00R

# While the Rails default wants to read secrets from environment variables in
# production, using Mina, this file is symlinked to shared/config/secrets.yml.
# So this file needs to be created with appropriate contents on the server.
# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
